import type { ApiEndpoint, ApiField, ApiGroup, ApiParam } from "./openapi";
const q = (name: string, description: string, required = false): ApiParam => ({ name, in: "query", description, required });
const f = (name: string, type: string, description: string, required = false): ApiField => ({ name, type, description, required });
const pages = [q("page", "Halaman mulai 1"), q("limit", "Jumlah per halaman, dibatasi server")];
const id = q("id", "ObjectId record", true);
const operation = (method: ApiEndpoint["method"], path: string, summary: string, auth: string, extra: Partial<ApiEndpoint> = {}): ApiEndpoint => ({ method, path, summary, description: summary + ". Validasi dan otorisasi tetap dijalankan server.", auth, ...extra });
export const API_UPDATES: ApiGroup[] = [
  { name: "Lisensi", description: "Status paket dan entitlement instalasi self-hosted.", endpoints: [
    operation("GET", "/license", "Status lisensi, aktivasi, dan fitur aktif", "Sesi pengguna aktif", { description: "Entitlement terverifikasi (Pro) dan ringkasan aktivasi (paket, masa lease). Tidak pernah mengirim license key atau activation secret." }),
    operation("POST", "/license", "Aktivasi lisensi, lepas lisensi, atau perbarui lease", "Superadmin", { description: "activate: ikat license key ke instalasi dan alamat website ini; fitur Pro langsung aktif pada image resmi. deactivate: lepas lisensi. refresh: minta lease baru. Maks 10 permintaan per 10 menit.", body: [f("action", "string", "activate | deactivate | refresh", true), f("licenseKey", "string", "Wajib untuk activate")] }),
    operation("GET", "/system/update", "Versi aplikasi dan pembaruan tersedia", "Superadmin (sesi)", { description: "Versi berjalan, versi terbaru dari website lisensi, metode pembaruan (pengelola installer, Dokploy API, atau webhook deploy) dan versi sebelumnya untuk rollback." }),
    operation("POST", "/system/update", "Mulai pembaruan atau kembalikan versi sebelumnya", "Superadmin (sesi)", { description: "update: pasang versi terbaru (atau version tertentu). rollback: kembali ke versi sebelumnya. Database tidak perlu langkah manual: tabel/kolom yang kurang ditambahkan saat start, data tidak dihapus.", body: [f("action", "string", "update | rollback", true), f("version", "string", "Versi tertentu, contoh 1.4.0 (opsional)")] }),
    operation("PUT", "/system/update", "Simpan tujuan pembaruan", "Superadmin (sesi)", { description: "mode dokploy: url, apiKey, composeId. mode webhook: url. Disimpan terenkripsi.", body: [f("mode", "string", "dokploy | webhook", true), f("url", "string", "Alamat Dokploy atau URL webhook", true), f("apiKey", "string", "API key Dokploy"), f("composeId", "string", "Compose ID Dokploy")] }),
    operation("DELETE", "/system/update", "Hapus tujuan pembaruan", "Superadmin (sesi)", { description: "Menghapus pengaturan Dokploy/webhook yang tersimpan." }),
    operation("GET", "/license/lease", "Lease bertanda tangan untuk agent lifecycle (internal)", "Bearer HRIS_AGENT_TOKEN", { description: "Hanya untuk agent di jaringan Docker. Agent memverifikasi tanda tangan sendiri; endpoint ini tidak memberi fitur." }),
    operation("GET", "/health", "Health check aplikasi dan database", "Publik", { description: "Digunakan container health check dan rollback otomatis; hanya mengembalikan status layanan." }),
  ] },
  { name: "Integrasi Pro", description: "Webhook keluar bertanda tangan. Tujuan wajib HTTPS publik dan redirect ditolak untuk mengurangi SSRF.", endpoints: [
    operation("GET", "/integrations/api-keys", "Daftar API key tanpa secret", "Pro integration.api + settings:read (sesi login saja)", { params: [q("view", "scopes: daftar scope yang boleh diberikan pemanggil")] }),
    operation("POST", "/integrations/api-keys", "Terbitkan API key", "Pro integration.api + settings:write", { body: [f("name", "string", "Nama integrasi", true), f("scopes", "array", "modul:aksi (mis. employees:read, leave:approve) atau employees.read; tidak boleh melebihi izin pembuat, modul settings tidak tersedia", true)] }),
    operation("PATCH", "/integrations/api-keys", "Aktif/nonaktifkan API key", "Pro integration.api + settings:write", { body: [f("id", "string", "ObjectId", true), f("enabled", "boolean", "Status baru", true)] }),
    operation("DELETE", "/integrations/api-keys", "Cabut API key", "Pro integration.api + settings:delete", { params: [id] }),
    operation("GET", "/integrations/employees", "Direktori karyawan minimal untuk integrasi", "Bearer API key dengan scope employees.read", { params: pages, description: "Tidak mengirim NIK, bank, payroll, tanggal lahir, atau data biometrik." }),
    operation("GET", "/integrations/webhooks", "Daftar webhook", "Pro integration.webhook + settings:read"),
    operation("POST", "/integrations/webhooks", "Buat webhook", "Pro integration.webhook + settings:write", { body: [f("name", "string", "3–120 karakter", true), f("url", "string", "URL HTTPS publik", true), f("events", "array", "discipline.case_created/decided, employee.updated, attendance.recorded, payroll.published", true), f("enabled", "boolean", "Aktif langsung")] }),
    operation("PATCH", "/integrations/webhooks", "Uji atau aktif/nonaktifkan webhook", "Pro integration.webhook + settings:write", { body: [f("id", "string", "ObjectId webhook", true), f("action", "string", "test | enable | disable", true)] }),
    operation("DELETE", "/integrations/webhooks", "Hapus webhook", "Pro integration.webhook + settings:delete", { params: [id] }),
  ] },
  { name: "Ulang Tahun", description: "Direktori internal karyawan aktif; kontak dan tanggal lahir lengkap tidak dikirim. Tahun lahir/usia hanya dikirim jika perusahaan mengaktifkannya.", endpoints: [operation("GET", "/birthdays", "Daftar ulang tahun sesuai periode perusahaan", "Sesi pengguna aktif", { params: pages, description: "page bilangan bulat >=1; limit 1–100. Respons data: today/from/to (tanggal kalender WIB), showBirthYearAndAge, total, items [{_id,name,month,day,occurrence,daysAway,birthYear?,ageAtOccurrence?}]. birthYear dan ageAtOccurrence hanya ada saat birthday_show_birth_year_age aktif; usia adalah usia pada occurrence. occurrence adalah tanggal perayaan pada periode pilihan, bukan tanggal lahir asli. Pengaturan birthday_window_mode: current_month/upcoming_months/custom_days; birthday_months_ahead 1–6; birthday_days_before/after 0–180. Batas tanggal inklusif; 29 Februari diperingati 28 Februari pada tahun nonkabisat." })] },
  { name: "Disiplin & SP", description: "Kasus wajib ditautkan ke karyawan. read untuk melihat, write untuk mencatat, approve untuk memutuskan. Lingkup reports hanya bawahan langsung; diri sendiri tidak boleh ditindak. Tidak otomatis mengubah status kerja.", endpoints: [
    operation("GET", "/discipline", "Daftar / rincian kasus dan direktori terbatas", "discipline:read; view=employees juga memerlukan write", { params: [...pages, q("id", "ID kasus untuk rincian terbaru"), q("employeeId", "Filter karyawan (tetap dibatasi scope)"), q("status", "open | issued | rejected | closed"), q("view", "access untuk izin UI; employees untuk direktori target"), q("q", "Nama/NIP direktori, maks 100 karakter")] }),
    operation("POST", "/discipline", "Catat kasus untuk karyawan", "discipline:write, lingkup target; bukan diri sendiri", { body: [f("employeeId", "string", "ObjectId karyawan", true), f("category", "string", "misconduct | fatal | separation", true), f("title", "string", "5–150 karakter", true), f("description", "string", "15–5000 karakter", true), f("evidence", "string", "Referensi bukti, maks 2000"), f("employeeStatement", "string", "Klarifikasi maks 3000"), f("action", "string", "coaching | warning | sp1 | sp2 | sp3 | termination | resignation | other", true), f("occurredAt", "string", "ISO datetime dengan offset", true)], example: { employeeId: "GANTI_ID_KARYAWAN", category: "misconduct", title: "Tinjauan kejadian", description: "Isi kronologi faktual yang telah diverifikasi.", action: "sp1", occurredAt: "2026-09-20T09:00:00+07:00" } }),
    operation("PATCH", "/discipline", "Putuskan / tutup kasus dengan revision check", "discipline:approve; lingkup target dan bukan diri sendiri", { body: [f("id", "string", "ObjectId kasus", true), f("revision", "number", "Versi dari GET terbaru", true), f("status", "string", "issued | rejected | closed", true), f("action", "string", "Tindakan; resignation hanya category separation", true), f("note", "string", "Dasar keputusan 15–3000 karakter", true), f("confirmed", "boolean", "Harus true setelah pemeriksaan manusia", true), f("effectiveAt", "string", "ISO datetime; wajib jika issued"), f("expiresAt", "string", "ISO datetime >= effectiveAt")], errors: [{ code: "409 CONFLICT", when: "Revisi usang / transisi tidak sah" }] }),
    operation("GET", "/discipline/employees/{id}", "Profil kerja karyawan penerima tindakan", "discipline:read sesuai lingkup", { description: "Hanya nama, NIP, status, jabatan, divisi, cabang dan atasan. Tidak membuka identitas pribadi/keuangan." }),
  ] },
  { name: "Ruang Uji Kebijakan", description: "Simulasi murni, tidak menulis payroll atau kasus disiplin.", endpoints: [
    operation("GET", "/payroll/simulate", "Direktori karyawan untuk simulasi", "payroll:read/all"),
    operation("POST", "/payroll/simulate", "Bandingkan potongan dengan rancangan aturan", "payroll:read/all", { body: [f("employeeId", "string", "ObjectId", true), f("period", "string", "YYYY-MM sejak 2000, tidak di masa depan", true), f("policy", "object", "latePerMinute, latePenaltyCap, absentPerDay wajib; lateUnit minute/hour/day; alphaEnabled; alphaAfterHours 0.01–24", true)], example: { employeeId: "GANTI_ID_KARYAWAN", period: "2026-08", policy: { latePerMinute: 1000, latePenaltyCap: 100000, absentPerDay: 50000, lateUnit: "minute", alphaEnabled: true, alphaAfterHours: 4 } } }),
  ] },
  { name: "Master dan Operasional Tambahan", description: "Operasi yang sebelumnya belum masuk katalog.", endpoints: [
    operation("GET", "/audit", "Baca log aktivitas", "audit:read/all atau settings:read/all", { params: [...pages, ...["module", "action", "from", "to", "q"].map((n) => q(n, "Filter; tanggal YYYY-MM-DD"))] }),
    operation("GET", "/divisions", "Daftar divisi", "Sesi pengguna"),
    operation("POST", "/divisions", "Tambah / ubah divisi", "settings:write", { body: [f("id", "string", "Isi untuk mengubah"), f("name", "string", "Nama divisi", true), f("headId", "string", "ObjectId kepala divisi"), f("branchId", "string", "ObjectId cabang")] }),
    operation("GET", "/positions", "Daftar jabatan", "Sesi pengguna"),
    operation("POST", "/positions", "Tambah / ubah jabatan", "settings:write", { body: [f("name", "string", "Nama jabatan", true), ...["id", "divisionId", "description", "jobdesk", "requirements", "location", "type", "status"].map((n) => f(n, "string", "Opsional; id untuk perubahan"))] }),
    operation("DELETE", "/employees", "Nonaktifkan karyawan dan akses login", "employees:delete/all", { params: [id] }),
    operation("DELETE", "/holidays", "Hapus hari libur", "settings:delete", { params: [q("dateKey", "YYYY-MM-DD", true)] }),
    operation("DELETE", "/notifications", "Hapus notifikasi sendiri yang telah dibaca", "Sesi pengguna"),
    operation("GET", "/regions", "Daftar provinsi / kabupaten / kecamatan", "Sesi pengguna", { params: [q("level", "provinces | regencies | districts", true), q("parent", "Kode induk wajib untuk regencies/districts")] }),
    operation("DELETE", "/roles", "Hapus peran non-sistem yang tidak dipakai", "settings:delete", { params: [id] }),
    operation("GET", "/branches/search", "Cari titik cabang atau koordinat", "settings:write/all", { params: [q("q", "3–160 karakter: cabang/alamat atau lat, lng", true)], description: "Cabang tersimpan dan koordinat tanpa vendor. Alamat eksternal memerlukan konfigurasi geocoding, cache dan pembatasan laju." }),
    ...["branches", "divisions", "positions"].map((name) => operation("DELETE", `/${name}/{id}`, `Hapus master ${name}`, "settings:delete")),
    operation("POST", "/branding/logo", "Unggah logo dokumen", "settings:write", { body: [f("dataUrl", "string", "Data URL gambar, maksimal 256 KiB", true)] }),
    operation("GET", "/branding", "Logo aplikasi tersimpan (Pro)", "settings:read", { description: "HRIS Pro dengan lisensi aktif. Community menolak dengan 403." }),
    operation("PUT", "/branding", "Simpan logo aplikasi (Pro)", "settings:write", { body: [f("logo", "string", "Data URL PNG/JPG/WebP, maksimal 300 KB", true), f("logoDark", "string", "Data URL logo tema gelap (opsional)"), f("mark", "string", "Data URL simbol 1:1 (opsional)")], description: "HRIS Pro dengan lisensi aktif. Community menolak dengan 403." }),
    operation("DELETE", "/branding", "Kembalikan logo bawaan (Pro)", "settings:write", { description: "HRIS Pro dengan lisensi aktif. Community menolak dengan 403." }),
    operation("POST", "/cron/daily", "Jalankan pemeliharaan harian", "x-cron-secret", { params: [{ name: "x-cron-secret", in: "header", required: true, description: "CRON_SECRET konfigurasi server. Berpotensi mengirim notifikasi/mengubah data." }] }),
    operation("GET", "/holidays/import", "Pratinjau impor libur nasional", "settings:read", { params: [q("year", "2000–2100", true)] }),
    operation("POST", "/holidays/import", "Terapkan tanggal libur terpilih", "settings:write", { body: [f("year", "number", "2000–2100", true), f("dateKeys", "string[]", "1–60 tanggal YYYY-MM-DD dari pratinjau", true)] }),
    operation("GET", "/settings/categories", "Daftar kategori inventaris", "Publik (implementasi lama; dapat menginisialisasi default)"),
    operation("POST", "/settings/categories", "Perbarui kategori inventaris", "settings:write", { body: [f("categories", "string[]", "Daftar kategori", true)] }),
    operation("GET", "/inventory", "Daftar aset dan penugasan terakhir", "inventory:read", { params: [...pages, ...["code", "q", "category"].map((n) => q(n, "Filter aset"))] }),
    operation("POST", "/inventory", "Tambah / ubah / tugaskan / kembalikan aset", "inventory:write", { body: [f("id", "string", "Isi untuk aset existing"), f("code", "string", "Kode unik wajib untuk baru"), f("name", "string", "Nama wajib untuk baru"), f("category", "string", "Kategori wajib untuk baru"), f("condition", "string", "Kondisi aset"), f("employeeId", "string", "Target penugasan"), f("action", "string", "return untuk pengembalian")] }),
    operation("GET", "/inventory/audit", "Daftar pemeriksaan aset", "inventory:read"),
    operation("POST", "/inventory/audit", "Catat pemeriksaan dan perbarui kondisi aset", "inventory:write", { body: [f("inventoryId", "string", "ObjectId aset", true), f("condition", "string", "Kondisi aset", true), f("notes", "string", "Catatan"), f("status", "string", "verified | flagged")] }),
    operation("GET", "/inventory/self", "Aset yang ditugaskan kepada diri sendiri", "Sesi karyawan"),
    operation("POST", "/inventory/self", "Tandatangani penerimaan aset sendiri", "Sesi karyawan pemilik penugasan", { body: [f("assignmentId", "string", "ObjectId penugasan pending_handover", true), f("signatureData", "string", "Data URL tanda tangan", true)] }),
  ] },
];
